name = "AccretionFormulae"
uuid = "31bec1c3-7af2-4563-a2e0-d36728d7d927"
authors = ["dangoh123", "kyle8mcknight <kyle-mcknight@hotmail.com>", "fjebaker <fergusbkr@gmail.com>", "phajy <andy.young@bristol.ac.uk>"]
version = "0.2.1"

[deps]
AccretionGeometry = "7f85384a-175b-40eb-971c-1f0b02ab1b9a"
CarterBoyerLindquist = "2b1461c5-fb25-4b94-b31c-0acab88ddff2"
GeodesicBase = "1f539516-e6d2-4f24-ab09-50f3ac3c4a5a"
GeodesicRendering = "dcac253f-9cde-4166-a841-20d11661ef48"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
CarterBoyerLindquist = ">=0.1.2"
GeodesicRendering = ">=0.2.1"
